[project]
name = "ny-voting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.3.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.0",
]
